[display]
separator = ": "
ascii_path = "~/.config/swiftfetch/ascii.txt"
ascii_color = "yellow"

[colors]
green = "#32CD32"
blue = "#1E90FF"
magenta = "#FF00FF"
yellow = "#E09A25"
red = "#FF4500"
cyan = "#00FFFF"
white = "#FFFFFF"

[[display.items]]
key = ""
type = "text"
value = ""

[[display.items]]
key = "user_info"
type = "default"
value = "user_info"
value_color = "white"

[[display.items]]
key = ""
type = "text"
value = "┌────────────────── System Information ───────────────────┐"
color = "yellow"

[[display.items]]
key = "           󰣇 ‣ os"
type = "default"
value = "os"
color = "yellow"
value_color = "white"

[[display.items]]
key = "           󰍛 ‣ kernel"
type = "default"
value = "kernel"
color = "yellow"
value_color = "white"

[[display.items]]
key = "            ‣ wm"
type = "default"
value = "wm"
color = "yellow"
value_color = "white"

[[display.items]]
key = "            ‣ editor"
type = "default"
value = "editor"
color = "yellow"
value_color = "white"

[[display.items]]
key = "            ‣ shell"
type = "default"
value = "shell"
color = "yellow"
value_color = "white"

[[display.items]]
key = "            ‣ term"
type = "default"
value = "terminal"
color = "yellow"
value_color = "white"

[[display.items]]
key = "            ‣ pkgs"
type = "default"
value = "pkg_count"
color = "yellow"
value_color = "white"

[[display.items]]
key = "            ‣ flat"
type = "default"
value = "flatpak_pkg_count"
color = "yellow"
value_color = "white"

[[display.items]]
key = ""
type = "text"
value = "├───────────────── Hardware Information ─────────────────┤"
color = "yellow"

[[display.items]]
key = "           󰍛 ‣ cpu"
type = "default"
value = "cpu"
color = "yellow"
value_color = "white"

[[display.items]]
key = "           󰓅 ‣ ram"
type = "default"
value = "memory"
color = "yellow"
value_color = "white"

[[display.items]]
key = ""
type = "text"
value = "├───────────────── Uptime Information ───────────────────┤"
color = "yellow"

[[display.items]]
key = "            ‣ uptime"
type = "default"
value = "uptime_seconds"
color = "yellow"
value_color = "white"

[[display.items]]
key = "            ‣ age"
type = "default"
value = "os_age"
color = "yellow"
value_color = "white"

[[display.items]]
key = ""
type = "text"
value = "└────────────────────────────────────────────────────────┘"
color = "yellow"
