# This is the new way of configuring swiftfetch.
# You're now able to use the "text" and "command" key.
#
# Example:
# [[display.items]]
# key = ""
# type = "text"
# value = ""
#
# You can leave the value & key empty for a new line. Else the key will be used as label and the value as text.
#
# Example:
# [[display.items]]
# key = ""
# type = "command"
# value = "free"
# color = 
#
# Here the key will be the label and the value will be the command that you want to run.

[display]
separator = ": "

[colors]
green = "#32CD32"
blue = "#1E90FF"
magenta = "#FF00FF"
yellow = "#FFD700"
red = "#FF4500"
cyan = "#00FFFF"

[[display.items]]
key = ""
type = "text"
value = ""

[[display.items]]
key = "user_info"
type = "default"
value = "user_info"

[[display.items]]
key = ""
type = "text"
value = "┌────────────────── System Information ───────────────────┐"
color = "yellow"

[[display.items]]
key = "           󰣇 ‣ os"
type = "default"
value = "os"
color = "yellow"

[[display.items]]
key = "           󰍛 ‣ kernel"
type = "default"
value = "kernel"
color = "yellow"

[[display.items]]
key = "            ‣ wm"
type = "default"
value = "wm"
color = "yellow"

[[display.items]]
key = "            ‣ editor"
type = "default"
value = "editor"
color = "yellow"

[[display.items]]
key = "            ‣ shell"
type = "default"
value = "shell"
color = "yellow"

[[display.items]]
key = "            ‣ term"
type = "default"
value = "terminal"
color = "yellow"

[[display.items]]
key = "            ‣ pkgs"
type = "default"
value = "pacman_pkg_count"
color = "yellow"

[[display.items]]
key = "            ‣ flat"
type = "default"
value = "flatpak_pkg_count"
color = "yellow"

[[display.items]]
key = ""
type = "text"
value = "├───────────────── Hardware Information ─────────────────┤"
color = "yellow"

[[display.items]]
key = "           󰍛 ‣ cpu"
type = "default"
value = "cpu"
color = "yellow"

[[display.items]]
key = "           󰓅 ‣ ram"
type = "default"
value = "memory"
color = "yellow"

[[display.items]]
key = ""
type = "text"
value = "├───────────────── Uptime Information ───────────────────┤"
color = "yellow"

[[display.items]]
key = "            ‣ uptime"
type = "default"
value = "uptime_seconds"
color = "yellow"

[[display.items]]
key = "            ‣ age"
type = "default"
value = "os_age"
color = "yellow"

[[display.items]]
key = ""
type = "text"
value = "└────────────────────────────────────────────────────────┘"
color = "yellow"

[[display.items]]
key = ""
type = "text"
value = ""
